#!/bin/sh

board="raspi3"
kernel="build/target/kernel8.img"
ioflags=""

case $1 in
	"m") ioflags="-serial null -serial stdio"; break;;
	"i") ioflags="-monitor stdio"; break;;
	*)	 ioflags="-serial stdio -serial null"; break;;
esac

qemu-system-aarch64 -M $board -kernel $kernel -display none $ioflags
