#ifndef ADDR_LOCAL_TIMER_H
#define ADDR_LOCAL_TIMER_H

#include <addresses/addr_base.h>

/*
 *	Page 196 of the BCM2835 ARM peripherals manual
 */
#define LOCAL_TIMER_BASE		(MMIO_BASE+0x0000B400)
#define LOCAL_TIMER_LOAD_REG	(LOCAL_TIMER_BASE+0x00)
#define LOCAL_TIMER_VAL_REG		(LOCAL_TIMER_BASE+0x04)
#define LOCAL_TIMER_CTRL_REG	(LOCAL_TIMER_BASE+0x08)
#define LOCAL_TIMER_IRQCA_REG	(LOCAL_TIMER_BASE+0x0C)
#define LOCAL_TIMER_RAWIRQ_REG	(LOCAL_TIMER_BASE+0x10)
#define LOCAL_TIMER_MASKIRQ_REG	(LOCAL_TIMER_BASE+0x14)
#define LOCAL_TIMER_RELOAD_REG	(LOCAL_TIMER_BASE+0x18)
#define LOCAL_TIMER_PDV_REG		(LOCAL_TIMER_BASE+0x1C)		// Pre-divider
#define LOCAL_TIMER_FRC_REG		(LOCAL_TIMER_BASE+0x20)		// Free-running counter


#endif /* ADDR_LOCAL_TIMER_H */
