#ifndef ADDR_MINI_UART_H
#define ADDR_MINI_UART_H

#include <addresses/addr_base.h>

#define MINI_UART_BASE		(MMIO_BASE+0x00215000)

#define AUX_IRQ				(MINI_UART_BASE+0x00)
#define AUX_ENABLES     	(MINI_UART_BASE+0x04)
#define AUX_MU_IO_REG   	(MINI_UART_BASE+0x40)
#define AUX_MU_IER_REG  	(MINI_UART_BASE+0x44)
#define AUX_MU_IIR_REG  	(MINI_UART_BASE+0x48)
#define AUX_MU_LCR_REG  	(MINI_UART_BASE+0x4C)
#define AUX_MU_MCR_REG  	(MINI_UART_BASE+0x50)
#define AUX_MU_LSR_REG  	(MINI_UART_BASE+0x54)
#define AUX_MU_MSR_REG  	(MINI_UART_BASE+0x58)
#define AUX_MU_SCRATCH  	(MINI_UART_BASE+0x5C)
#define AUX_MU_CNTL_REG 	(MINI_UART_BASE+0x60)
#define AUX_MU_STAT_REG 	(MINI_UART_BASE+0x64)
#define AUX_MU_BAUD_REG 	(MINI_UART_BASE+0x68)


#endif /* ADDR_MINI_UART_H */
